/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import com.example.Backend.ConectaFirebase;
import com.example.Backend.VerificaEmail;

/**
 *
 * @author Rason
 */
public class CadastroProfissionalFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroProfissionalFrame
     */
    VerificaEmail verificaEmail = new VerificaEmail();
    ConectaFirebase conecta = new ConectaFirebase();
    ArrayList<String> profissoes = new ArrayList<String>();
    Icone icone = new Icone();

    public CadastroProfissionalFrame() {
        initComponents();
        revelaSenha.setIcon(icone.getOlhoFechado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        sobrenomeText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoText = new javax.swing.JTextArea();
        emailText = new javax.swing.JTextField();
        senhaText = new javax.swing.JPasswordField();
        revelaSenha = new javax.swing.JButton();
        cadastrarButton = new javax.swing.JButton();
        encanadorBox = new javax.swing.JCheckBox();
        eletricistaBox = new javax.swing.JCheckBox();
        pedreiroBox = new javax.swing.JCheckBox();
        diaristaBox = new javax.swing.JCheckBox();
        limpaTapeteBox = new javax.swing.JCheckBox();
        limpaPiscinaBox = new javax.swing.JCheckBox();
        avisoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro do profissional");

        nomeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTextActionPerformed(evt);
            }
        });

        descricaoText.setColumns(20);
        descricaoText.setRows(5);
        jScrollPane1.setViewportView(descricaoText);

        revelaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revelaSenhaActionPerformed(evt);
            }
        });

        cadastrarButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cadastrarButton.setText("Cadastrar");
        cadastrarButton.setToolTipText("");
        cadastrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtonActionPerformed(evt);
            }
        });

        encanadorBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        encanadorBox.setText("Encanador");

        eletricistaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eletricistaBox.setText("Eletricista");

        pedreiroBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pedreiroBox.setText("Pedreiro");
        pedreiroBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedreiroBoxActionPerformed(evt);
            }
        });

        diaristaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        diaristaBox.setText("Diarista");

        limpaTapeteBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpaTapeteBox.setText("Limpador de tapete");

        limpaPiscinaBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        limpaPiscinaBox.setText("Limpador de piscina");

        avisoLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Sobrenome:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Descrição:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Senha:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Profissões");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastrarButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(encanadorBox)
                        .addGap(18, 18, 18)
                        .addComponent(eletricistaBox))
                    .addComponent(avisoLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pedreiroBox)
                            .addComponent(diaristaBox))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(limpaPiscinaBox)
                            .addComponent(limpaTapeteBox)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nomeText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                        .addComponent(sobrenomeText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(senhaText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(revelaSenha))
                        .addComponent(emailText, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(revelaSenha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encanadorBox)
                    .addComponent(eletricistaBox)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(limpaTapeteBox, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pedreiroBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diaristaBox)
                    .addComponent(limpaPiscinaBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(avisoLabel)
                .addGap(18, 18, 18)
                .addComponent(cadastrarButton)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void revelaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revelaSenhaActionPerformed
        if (revelaSenha.getIcon().equals(icone.getOlhoAberto())) {
            senhaText.setEchoChar('*');
            revelaSenha.setIcon(icone.getOlhoFechado());
            repaint();
        } else {
            senhaText.setEchoChar('\u0000');
            revelaSenha.setIcon(icone.getOlhoAberto());
            repaint();
        }
    }//GEN-LAST:event_revelaSenhaActionPerformed

    private void nomeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTextActionPerformed

    private void pedreiroBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pedreiroBoxActionPerformed

    }// GEN-LAST:event_pedreiroBoxActionPerformed

    private void cadastrarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastrarButtonActionPerformed
        String aviso = "";
        profissoes.clear();
        //profissoes
        if(encanadorBox.isSelected())
        profissoes.add("Encanador");
        if(eletricistaBox.isSelected())
        profissoes.add("Eletricista");
        if(pedreiroBox.isSelected())
        profissoes.add("Pedreiro");
        if(limpaTapeteBox.isSelected())
        profissoes.add("Limpador de tapete");
        if(diaristaBox.isSelected())
        profissoes.add("Diarista");
        if(limpaPiscinaBox.isSelected())
        profissoes.add("Limpador de piscina");
        if(profissoes.size()==0)
        aviso = "Escolha alguma profissão";
        //descrição
        int cont = 0;
        for(char c :descricaoText.getText().trim().toCharArray())
            if(c==' ')cont++;

        if (descricaoText.getText().trim().length() == 0)
            aviso = "Descrição obrigatória";
            else if(cont<2)
            aviso = "Coloque uma descrição maior";
        // senha
        if (senhaText.getPassword().length < 6)
            aviso = "Senha menor que 6 caracteres";

        // email
        if (!verificaEmail.isVerified(emailText.getText()))
            aviso = "Email inválido";
        // sobrenome
        if (sobrenomeText.getText().trim().length() == 0)
            aviso = "Sobrenome obrigatório";
        else if (sobrenomeText.getText().trim().contains(" "))
            aviso = "Sobrenome contém espaço";

        // nome
        if (nomeText.getText().trim().length() == 0)
            aviso = "Nome obrigatório";
        else if (nomeText.getText().trim().contains(" "))
            aviso = "Nome contém espaço";

        avisoLabel.setText(aviso);
        repaint();

        if (avisoLabel.getText().length() == 0)
            try {
                boolean cadastrado = conecta.inserirDadosProfissional(nomeText.getText() + " " + sobrenomeText.getText(),
                        emailText.getText(),descricaoText.getText(), String.valueOf(senhaText.getPassword()),profissoes);
                dispose();
                JOptionPane.showMessageDialog(null, cadastrado ? "Cadastrado com sucesso" : "Email já cadastrado");
                new HomeFrames().setVisible(true);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
    }// GEN-LAST:event_cadastrarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProfissionalFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProfissionalFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProfissionalFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProfissionalFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProfissionalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JButton cadastrarButton;
    private javax.swing.JTextArea descricaoText;
    private javax.swing.JCheckBox diaristaBox;
    private javax.swing.JCheckBox eletricistaBox;
    private javax.swing.JTextField emailText;
    private javax.swing.JCheckBox encanadorBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox limpaPiscinaBox;
    private javax.swing.JCheckBox limpaTapeteBox;
    private javax.swing.JTextField nomeText;
    private javax.swing.JCheckBox pedreiroBox;
    private javax.swing.JButton revelaSenha;
    private javax.swing.JPasswordField senhaText;
    private javax.swing.JTextField sobrenomeText;
    // End of variables declaration//GEN-END:variables
}
