/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.awt.Color;

import javax.swing.JOptionPane;

import com.example.Backend.ConectaFirebase;
import com.example.Backend.VerificaEmail;

/**
 *
 * @author Rason
 */
public class CadastroClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFrame
     */
    Icone icone = new Icone();
    VerificaEmail verificaEmail = new VerificaEmail();
    ConectaFirebase conecta = new ConectaFirebase();

    public CadastroClienteFrame() {
        initComponents();
        revelaSenha.setIcon(icone.getOlhoFechado());
        avisoLabel.setForeground(Color.RED);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        sobrenome = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        senha = new javax.swing.JLabel();
        nomeText = new javax.swing.JTextField();
        sobrenomeText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        senhaText = new javax.swing.JPasswordField();
        cadastrar = new javax.swing.JButton();
        revelaSenha = new javax.swing.JButton();
        avisoLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro do cliente");

        nome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nome.setText("Nome:");

        sobrenome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sobrenome.setText("Sobrenome:");

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("Email:");

        senha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        senha.setText("Senha:");

        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cadastrar.setText("Cadastrar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        revelaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revelaSenhaActionPerformed(evt);
            }
        });

        avisoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Não coloque espaço na senha");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sobrenome)
                    .addComponent(nome)
                    .addComponent(email)
                    .addComponent(senha))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cadastrar)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomeText, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                            .addComponent(sobrenomeText)
                            .addComponent(emailText)
                            .addComponent(senhaText))
                        .addGap(18, 18, 18)
                        .addComponent(revelaSenha))
                    .addComponent(jLabel2)
                    .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(nomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sobrenome)
                    .addComponent(sobrenomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(revelaSenha)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(senha)
                        .addComponent(senhaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(avisoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrar)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 dispose();
        new HomeFrames().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void revelaSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_revelaSenhaActionPerformed
        if (revelaSenha.getIcon().equals(icone.getOlhoAberto())) {
            senhaText.setEchoChar('*');
            revelaSenha.setIcon(icone.getOlhoFechado());
            repaint();
        } else {
            senhaText.setEchoChar('\u0000');
            revelaSenha.setIcon(icone.getOlhoAberto());
            repaint();
        }
    }// GEN-LAST:event_revelaSenhaActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_emailTextActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cadastrarActionPerformed
        String aviso = "";
        // senha
        if (senhaText.getPassword().length < 6)
            aviso = "Senha menor que 6 caracteres";

        // email
        if (!verificaEmail.isVerified(emailText.getText()))
            aviso = "Email inválido";
        // sobrenome
        if (sobrenomeText.getText().trim().length() == 0)
            aviso = "Sobrenome obrigatório";
        else if (sobrenomeText.getText().trim().contains(" "))
            aviso = "Sobrenome contém espaço";

        // nome
        if (nomeText.getText().trim().length() == 0)
            aviso = "Nome obrigatório";
        else if (nomeText.getText().trim().contains(" "))
            aviso = "Nome contém espaço";

            avisoLabel.setText(aviso);
           repaint();

        if (avisoLabel.getText().length() == 0) 
            try {
                boolean cadastrado = conecta.inserirDadosCliente(nomeText.getText() + " " + sobrenomeText.getText(),
                        emailText.getText(), String.valueOf(senhaText.getPassword()));
                        dispose();
                JOptionPane.showMessageDialog(null, cadastrado ? "Cadastrado com sucesso" : "Email já cadastrado");
                new HomeFrames().setVisible(true);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        
    }// GEN-LAST:event_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
new CadastroClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nomeText;
    private javax.swing.JButton revelaSenha;
    private javax.swing.JLabel senha;
    private javax.swing.JPasswordField senhaText;
    private javax.swing.JLabel sobrenome;
    private javax.swing.JTextField sobrenomeText;
    // End of variables declaration//GEN-END:variables
}
