/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.util.ArrayList;

import javax.swing.JOptionPane;

import com.example.Backend.Avaliacao;
import com.example.Backend.ConectaFirebase;
import com.example.Backend.CurrentUser;
import com.example.Backend.HistDaoCliente;
import com.example.Backend.StarRater;
import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;

/**
 *
 * @author Rason
 */
public class HistClienteFrame extends javax.swing.JFrame {

    /**
     * Creates new form HistClienteFrame
     */
    ArrayList<HistDaoCliente> histCliente;
    ListaHistCliente tableModel;
    Object[] rating = { 0, 0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5 };

    public HistClienteFrame() {
        this.histCliente = new ArrayList<HistDaoCliente>();
        getHistDaoCliente();

        tableModel = new ListaHistCliente(this.histCliente);

        initComponents();

        histClienteLista.setModel(tableModel);
    }

    public void getHistDaoCliente() {

        ApiFuture<QuerySnapshot> query = ConectaFirebase.bd.collection("histórico").get();

        try {
            for(DocumentSnapshot doc : query.get().getDocuments()){
                ArrayList aux = ((ArrayList)doc.get("informações"));
                if(aux.get(0).toString().equals(CurrentUser.uid))
                this.histCliente.add(new HistDaoCliente(aux.get(3).toString(), aux.get(5).toString(),
               aux.get(2).toString(),aux.get(12).toString(), (boolean)aux.get(9),(boolean)aux.get(11)));
            }
        } catch (Exception e) {
            //TODO: handle exception
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        histClienteLista = new javax.swing.JTable();
        avaliaButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        histClienteLista.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(histClienteLista);

        avaliaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avaliaButton.setText("Avaliar");
        avaliaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaliaButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(avaliaButton)
                                        .addComponent(voltarButton))
                                .addGap(68, 68, 68)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(avaliaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(voltarButton)
                                .addGap(37, 37, 37)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void avaliaButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_avaliaButtonActionPerformed
        int row = histClienteLista.getSelectedRow();

        if ( row>= 0&&tableModel.isServicoTerminado(row)&&!tableModel.isAvaliou(row)) {
            dispose();
            Object aux = JOptionPane.showInputDialog(null, "Avalie o profissional " + tableModel.lista.get(row).getNomeProfissional(), null,
                    JOptionPane.PLAIN_MESSAGE, null, rating, 5);
            Double d;
            if (aux == null)
                d = 5.0;
            else
                d = Double.parseDouble(String.valueOf(aux));
            new Avaliacao(tableModel.getIdProfissional(row),
                    tableModel.getIdDoc(row), d);
        }
    }// GEN-LAST:event_avaliaButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_voltarButtonActionPerformed
        dispose();
        new HomeFrames().setVisible(true);// TODO add your handling code here:
    }// GEN-LAST:event_voltarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistClienteFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistClienteFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avaliaButton;
    private javax.swing.JTable histClienteLista;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
