/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.util.ArrayList;

import com.example.Backend.ConectaFirebase;
import com.example.Backend.CurrentUser;
import com.example.Backend.HistDaoProfissional;
import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;

/**
 *
 * @author Rason
 */
public class HistProfissionalFrame extends javax.swing.JFrame {

        /**
         * Creates new form HistProfissionalFrame
         */
        ArrayList<HistDaoProfissional> histProf;
        ListaHistProf tableModelProf;

        public HistProfissionalFrame() {
                this.histProf = new ArrayList<HistDaoProfissional>();
                getHistDaoProf();

                this.tableModelProf = new ListaHistProf(this.histProf);
                System.out.println(histProf.size());

                initComponents();

                listaHistProf.setModel(tableModelProf);
        }

        public void getHistDaoProf() {
                ApiFuture<QuerySnapshot> query = ConectaFirebase.bd.collection("histórico").get();

                try {

                        for (DocumentSnapshot doc : query.get().getDocuments()) {

                                ArrayList aux = ((ArrayList) doc.get("informações"));
                                if (aux.get(2).toString().equals(CurrentUser.uid)) {
                                        System.out.println("qw");
                                        this.histProf.add(new HistDaoProfissional((String) aux.get(1),
                                                        (String) aux.get(6),
                                                        (double) aux.get(7), (String) aux.get(4), (String) aux.get(5),
                                                        (String) aux.get(12),
                                                        (boolean) aux.get(9)));
                                }
                        }

                } catch (Exception e) {
                        // TODO: handle exception
                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane1 = new javax.swing.JScrollPane();
                listaHistProf = new javax.swing.JTable();
                jLabel1 = new javax.swing.JLabel();
                attButton = new javax.swing.JButton();
                jButton1 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                listaHistProf.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null },
                                                { null, null, null, null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6",
                                                "Title 7"
                                }));
                jScrollPane1.setViewportView(listaHistProf);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jLabel1.setText(
                                "<html>Clique em uma linha da lista para<br> indicar que você terminou<br> aquele trabalho e em seguida<br> clique no botão abaixo</html>");

                attButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                attButton.setText("Atualizar");

                jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                jButton1.setText("Voltar");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                751,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(attButton)
                                                                                .addComponent(jButton1))
                                                                .addContainerGap(261, Short.MAX_VALUE)));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jScrollPane1,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                547,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addContainerGap())
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                .addComponent(jLabel1,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(18, 18, 18)
                                                                                                .addComponent(attButton)
                                                                                                .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                Short.MAX_VALUE)
                                                                                                .addComponent(jButton1)
                                                                                                .addGap(14, 14, 14)))));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(HistProfissionalFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(HistProfissionalFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(HistProfissionalFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(HistProfissionalFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new HistProfissionalFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton attButton;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTable listaHistProf;
        // End of variables declaration//GEN-END:variables
}
