/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.TableCellRenderer;
import javax.swing.text.DefaultStyledDocument;

import com.example.Backend.ConectaFirebase;
import com.example.Backend.CurrentUser;
import com.example.Backend.Notificacao;
import com.example.Backend.ProfissionalManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rason
 */
public class HomeFrames extends javax.swing.JFrame {

    /**
     * Creates new form HomeFrames
     */
    ListaTableModel tableModel = new ListaTableModel();
    ConectaFirebase conecta = new ConectaFirebase();

    DefaultStyledDocument doc;
    ProfissionalManager prof = new ProfissionalManager();
    ArrayList<String> listaProfissionais = new ArrayList<String>();
    Object[] opC = { "Mudar nome", "Mudar senha" };
    Object[] opP = { "Mudar nome", "Mudar senha", "Mostrar avaliação", "Mostrar faturamento" };

    public HomeFrames() {
        // initComponents();

        try {

            if (conecta.bd == null)
                conecta.conectarDB();

        } finally {
            initComponents();
            prof.attListaProfissionais();

            jLabel1.setText(CurrentUser.uid == null ? "Você não está logado" : multilineName(CurrentUser.nome));
            buttonLogaDesloga.setText(CurrentUser.uid == null ? "Login" : "Deslogar");

            jListaProfissionais.setModel(tableModel);
        }
    }

    private String multilineName(String name) {
        String formated = name.substring(0, name.length()) + "<br>";
        if (name.length() > 35)
            formated = name.substring(36, name.length()) + "<br>";
        return "<html>Bem-vindo,<br>" + formated + "</html>";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListaProfissionais = new javax.swing.JTable();
        contrataButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonLogaDesloga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pesquisaButton = new javax.swing.JButton();
        procuraText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pedreiroBox = new javax.swing.JCheckBox();
        encanadorBox = new javax.swing.JCheckBox();
        eletricistaBox = new javax.swing.JCheckBox();
        diaristaBox = new javax.swing.JCheckBox();
        limpaTapeteBox = new javax.swing.JCheckBox();
        limpaPiscinaBox = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        notButton = new javax.swing.JButton();
        histButton = new javax.swing.JButton();
        perfilButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jListaProfissionais.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }));
        jScrollPane1.setViewportView(jListaProfissionais);

        contrataButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contrataButton.setText("Contrata");
        contrataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrataButtonActionPerformed(evt);
            }
        });

        buttonLogaDesloga.setText("jButton2");
        buttonLogaDesloga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogaDeslogaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(buttonLogaDesloga)
                                                .addGap(0, 98, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23,
                                        Short.MAX_VALUE)
                                .addComponent(buttonLogaDesloga)
                                .addContainerGap()));

        pesquisaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pesquisaButton.setText("Pesquisar");
        pesquisaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaButtonActionPerformed(evt);
            }
        });

        procuraText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Pesquisar profissão:");

        pedreiroBox.setText("Pedreiro");
        pedreiroBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedreiroBoxActionPerformed(evt);
            }
        });

        encanadorBox.setText("Encanador");
        encanadorBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encanadorBoxActionPerformed(evt);
            }
        });

        eletricistaBox.setText("Eletricista");
        eletricistaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eletricistaBoxActionPerformed(evt);
            }
        });

        diaristaBox.setText("Diarista");
        diaristaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaristaBoxActionPerformed(evt);
            }
        });

        limpaTapeteBox.setText("Limpador de tapete");
        limpaTapeteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaTapeteBoxActionPerformed(evt);
            }
        });

        limpaPiscinaBox.setText("Limpador de piscina");
        limpaPiscinaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaPiscinaBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("<html>Selecione o profissional na lista ao lado<br> para poder contratá-lo</html>");

        notButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        notButton.setText("Notificação");
        notButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notButtonActionPerformed(evt);
            }
        });

        histButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        histButton.setText("Histórico");
        histButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histButtonActionPerformed(evt);
            }
        });

        perfilButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perfilButton.setText("Perfil");
        perfilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfilButtonActionPerformed(evt);
            }
        });

        jButton1.setText("LoginCliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("LoginProfissional");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(contrataButton)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(notButton)
                                                        .addComponent(histButton)
                                                        .addComponent(perfilButton))
                                                .addGap(108, 108, 108))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jButton2)
                                                        .addComponent(jButton1))
                                                .addGap(99, 99, 99)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator1)
                                        .addComponent(procuraText)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pesquisaButton)
                                                        .addComponent(jLabel2)
                                                        .addComponent(pedreiroBox)
                                                        .addComponent(encanadorBox)
                                                        .addComponent(eletricistaBox)
                                                        .addComponent(diaristaBox)
                                                        .addComponent(limpaTapeteBox)
                                                        .addComponent(limpaPiscinaBox))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545,
                                                Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(contrataButton)
                                                .addGap(26, 26, 26)
                                                .addComponent(jButton1)
                                                .addGap(38, 38, 38)
                                                .addComponent(notButton)
                                                .addGap(8, 8, 8)
                                                .addComponent(jButton2)
                                                .addGap(52, 52, 52)
                                                .addComponent(histButton)
                                                .addGap(61, 61, 61)
                                                .addComponent(perfilButton)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(procuraText, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisaButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(pedreiroBox)
                                .addGap(18, 18, 18)
                                .addComponent(encanadorBox)
                                .addGap(18, 18, 18)
                                .addComponent(eletricistaBox)
                                .addGap(18, 18, 18)
                                .addComponent(diaristaBox)
                                .addGap(18, 18, 18)
                                .addComponent(limpaTapeteBox)
                                .addGap(18, 18, 18)
                                .addComponent(limpaPiscinaBox)
                                .addGap(0, 0, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void perfilButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_perfilButtonActionPerformed
        if (CurrentUser.uid != null) {
            Object option;
            if (CurrentUser.cliente) {
                dispose();
                option = JOptionPane.showInputDialog(null, "O que você deseja fazer?", null, JOptionPane.PLAIN_MESSAGE,
                        null, opC, 1);
                dispose();
                switch (option.toString()) {
                    case "Mudar nome":

                        break;
                    case "Mudar senha":
                        new MudarSenhaFrame().setVisible(true);
                        break;
                    default:
                        break;
                }

            } else {
                dispose();
                option = JOptionPane.showInputDialog(null, "O que você deseja fazer?", null, JOptionPane.PLAIN_MESSAGE,
                        null, opP, 1);
                dispose();
                switch (option.toString()) {
                    case "Mudar nome":
                        break;
                    case "Mudar senha":
                        new MudarSenhaFrame().setVisible(true);
                        break;
                    case "Mostrar avaliação":
                        break;
                    case "Mostrar faturamento":
                        break;
                }
            }
        }
    }// GEN-LAST:event_perfilButtonActionPerformed

    private void notButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_notButtonActionPerformed
        if (CurrentUser.uid != null) {
            try {
                dispose();
                new Notificacao().verificaMensagem(CurrentUser.cliente);
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        }
    }// GEN-LAST:event_notButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        try {
            new CurrentUser();
            conecta.login("joaorailson7@gmail.com", "123456");

        } catch (Exception ex) {
            Logger.getLogger(HomeFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        try {
            new CurrentUser();
            conecta.login("joao.railson.costa60@aluno.ifce.edu.br", "123456");

        } catch (Exception ex) {
            Logger.getLogger(HomeFrames.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void histButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_histButtonActionPerformed
        if (CurrentUser.uid != null) {
            if (CurrentUser.cliente) {
                dispose();
                new HistClienteFrame().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Botão com problemas");
                /*
                 * dispose();
                 * new HistProfissionalFrame().setVisible(true);
                 */
            }
        }
    }// GEN-LAST:event_histButtonActionPerformed

    private void pesquisaButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pesquisaButtonActionPerformed
        pedreiroBox.setSelected(false);
        encanadorBox.setSelected(false);
        eletricistaBox.setSelected(false);
        diaristaBox.setSelected(false);
        limpaTapeteBox.setSelected(false);
        limpaPiscinaBox.setSelected(false);
        listaProfissionais.clear();
        prof.procuraProfissional(procuraText.getText());
        repaint();
    }// GEN-LAST:event_pesquisaButtonActionPerformed

    private void pedreiroBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_pedreiroBoxActionPerformed
        procuraText.setText("");
        if (pedreiroBox.isSelected())
            listaProfissionais.add("Pedreiro");
        else
            listaProfissionais.remove("Pedreiro");
        prof.procuraProfissional(listaProfissionais);
        repaint();
    }// GEN-LAST:event_pedreiroBoxActionPerformed

    private void encanadorBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_encanadorBoxActionPerformed

        procuraText.setText("");

        if (encanadorBox.isSelected())
            listaProfissionais.add("Encanador");
        else
            listaProfissionais.remove("Encanador");
        prof.procuraProfissional(listaProfissionais);
        repaint();
    }// GEN-LAST:event_encanadorBoxActionPerformed

    private void eletricistaBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_eletricistaBoxActionPerformed
        procuraText.setText("");
        if (eletricistaBox.isSelected())
            listaProfissionais.add("Eletricista");
        else
            listaProfissionais.remove("Eletricista");
        prof.procuraProfissional(listaProfissionais);
        repaint();
    }// GEN-LAST:event_eletricistaBoxActionPerformed

    private void diaristaBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_diatistaBoxActionPerformed
        procuraText.setText("");
        if (diaristaBox.isSelected())
            listaProfissionais.add("Diarista");
        else
            listaProfissionais.remove("Diarista");
        prof.procuraProfissional(listaProfissionais);
        repaint();
    }// GEN-LAST:event_diatistaBoxActionPerformed

    private void limpaTapeteBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limpaTapeteBoxActionPerformed
        procuraText.setText("");
        if (limpaTapeteBox.isSelected())
            listaProfissionais.add("Limpador de tapete");
        else
            listaProfissionais.remove("Limpador de tapete");
        prof.procuraProfissional(listaProfissionais);
        repaint();
    }// GEN-LAST:event_limpaTapeteBoxActionPerformed

    private void limpaPiscinaBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_limpaPiscinaBoxActionPerformed
        procuraText.setText("");
        if (limpaPiscinaBox.isSelected())
            listaProfissionais.add("Limpador de piscina");
        else
            listaProfissionais.remove("Limpador de piscina");
        prof.procuraProfissional(listaProfissionais);
        repaint();
    }// GEN-LAST:event_limpaPiscinaBoxActionPerformed

    private void buttonLogaDeslogaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_buttonLogaDeslogaActionPerformed

        if (CurrentUser.uid == null) {
            new LoginFrame().setVisible(true);
            dispose();
        } else {
            new CurrentUser();
            repaint();
        }

        jLabel1.setText(CurrentUser.uid == null ? "Você não está logado" : "Bem vindo, " + CurrentUser.nome);
        buttonLogaDesloga.setText(CurrentUser.uid == null ? "Login" : "Deslogar");

    }// GEN-LAST:event_buttonLogaDeslogaActionPerformed

    private void contrataButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed

        if (CurrentUser.uid != null && !CurrentUser.uid
                .equals((String) jListaProfissionais.getValueAt(jListaProfissionais.getSelectedRow(), 4))
                && jListaProfissionais.getSelectedRow() >= 0) {
            new ContrataFrame(CurrentUser.uid,
                    (String) jListaProfissionais.getValueAt(jListaProfissionais.getSelectedRow(), 4)).setVisible(true);
            dispose();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrames.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrames.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrames.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrames.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrames().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogaDesloga;
    private javax.swing.JButton contrataButton;
    private javax.swing.JCheckBox diaristaBox;
    private javax.swing.JCheckBox eletricistaBox;
    private javax.swing.JCheckBox encanadorBox;
    private javax.swing.JButton histButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTable jListaProfissionais;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox limpaPiscinaBox;
    private javax.swing.JCheckBox limpaTapeteBox;
    private javax.swing.JButton notButton;
    private javax.swing.JCheckBox pedreiroBox;
    private javax.swing.JButton perfilButton;
    private javax.swing.JButton pesquisaButton;
    private javax.swing.JTextField procuraText;
    // End of variables declaration//GEN-END:variables

}