/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.util.Map;

import javax.swing.JOptionPane;

import com.example.Backend.ConectaFirebase;
import com.example.Backend.CurrentUser;
import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;

/**
 *
 * @author Rason
 */
public class MudarSenhaFrame extends javax.swing.JFrame {

    /**
     * Creates new form MudarSenhaFrame
     */
    Icone icone = new Icone();

    public MudarSenhaFrame() {
        initComponents();
        revelaSenha1.setIcon(icone.getOlhoFechado());
        revelaSenha2.setIcon(icone.getOlhoFechado());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        senhaText1 = new javax.swing.JPasswordField();
        senhaText2 = new javax.swing.JPasswordField();
        revelaSenha1 = new javax.swing.JButton();
        revelaSenha2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        avisoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Senha antiga:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Nova senha:");

        revelaSenha1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revelaSenha1ActionPerformed(evt);
            }
        });

        revelaSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revelaSenha2ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Trocar senha");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        avisoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avisoLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(avisoLabel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jButton1)
                                                        .addGroup(layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(senhaText2,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 147,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(senhaText1)))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(revelaSenha1)
                                                        .addComponent(revelaSenha2))))
                                .addContainerGap(77, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(revelaSenha1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel1)
                                                .addComponent(senhaText1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(revelaSenha2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2)
                                                .addComponent(senhaText2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35,
                                        Short.MAX_VALUE)
                                .addComponent(avisoLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addGap(25, 25, 25)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        String aviso = "";
        if (senhaText1.getPassword().length < 6)
            aviso = "Digite a senha antiga";
        if (senhaText2.getPassword().length < 6)
            aviso = "Digite a senha nova";

        if (!senhaText2.getPassword().equals(senhaText1.getPassword()))
            aviso = "Senhas não combinam";
        avisoLabel.setText(aviso);
        repaint();

        if (aviso.length() == 0) {
            String id = CurrentUser.uid, novaSenha = String.valueOf(senhaText2.getPassword()),
                    senhaAntiga = String.valueOf(senhaText1.getPassword());

            ApiFuture<QuerySnapshot> query = ConectaFirebase.bd.collection("clientes").get();
            try {
                for (DocumentSnapshot doc : query.get().getDocuments()) {
                    if (doc.getId().equals(id)) {
                        Map<String, Object> params = doc.getData();

                        if (senhaAntiga.equals(params.get("senha"))) {
                            params.replace("senha", novaSenha);
                            DocumentReference docRef = ConectaFirebase.bd.collection("clientes").document(doc.getId());
                            docRef.update(params);
                            JOptionPane.showMessageDialog(null, "Senha modificada");
                        } else {
                            aviso = "Senha antiga não encontrada";
                            repaint();
                        }
                    }

                }

                query = ConectaFirebase.bd.collection("profissionais").get();
                for (DocumentSnapshot doc : query.get().getDocuments()) {
                    if (doc.getId().equals(id)) {
                        Map<String, Object> params = doc.getData();
                        if (senhaAntiga.equals(params.get("senha"))) {
                            params.replace("senha", novaSenha);
                            DocumentReference docRef = ConectaFirebase.bd.collection("profissionais")
                                    .document(doc.getId());
                            docRef.update(params);
                            JOptionPane.showMessageDialog(null, "Senha modificada");

                        } else {
                            aviso = "Senha antiga não encontrada";
                            repaint();
                        }

                    }
                }
            } catch (Exception e) {
                // TODO: handle exception
            }

        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void revelaSenha2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_revelaSenha2ActionPerformed
        if (revelaSenha2.getIcon().equals(icone.getOlhoAberto())) {
            senhaText2.setEchoChar('*');
            revelaSenha2.setIcon(icone.getOlhoFechado());
            repaint();
        } else {
            senhaText2.setEchoChar('\u0000');
            revelaSenha2.setIcon(icone.getOlhoAberto());
            repaint();
        } // TODO add your handling code here:
    }// GEN-LAST:event_revelaSenha2ActionPerformed

    private void revelaSenha1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_revelaSenha1ActionPerformed
        if (revelaSenha1.getIcon().equals(icone.getOlhoAberto())) {
            senhaText1.setEchoChar('*');
            revelaSenha1.setIcon(icone.getOlhoFechado());
            repaint();
        } else {
            senhaText1.setEchoChar('\u0000');
            revelaSenha1.setIcon(icone.getOlhoAberto());
            repaint();
        } // TODO add your handling code here:
    }// GEN-LAST:event_revelaSenha1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MudarSenhaFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MudarSenhaFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MudarSenhaFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MudarSenhaFrame.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MudarSenhaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton revelaSenha1;
    private javax.swing.JButton revelaSenha2;
    private javax.swing.JPasswordField senhaText1;
    private javax.swing.JPasswordField senhaText2;
    // End of variables declaration//GEN-END:variables
}
