/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.example.Design;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;

import javax.swing.JOptionPane;

import com.example.Backend.ConectaFirebase;
import com.example.Backend.Historico;
import com.example.Backend.TesteVeto;
import com.github.lgooddatepicker.components.TimePickerSettings;
import com.google.cloud.firestore.DocumentReference;

/**
 *
 * @author Rason
 */
public class ProfissionalDataFrame extends javax.swing.JFrame {

    /**
     * Creates new form ProfissionalDataFrame
     */
    Object dia1 = "28/03/2022 13:00", dia2 = "29/03/2022 18:00";
    Date diaInicial, diaFinal;
    LocalTime horaInicial, horaFinal;
    ArrayList<Object> mensagem;
    TimePickerSettings setting = new TimePickerSettings();

    public ProfissionalDataFrame(ArrayList<Object> mensagem) {
        this.mensagem = mensagem;
        addInfo(mensagem.get(7), mensagem.get(8));

        initComponents();
        setting.setVetoPolicy(new TesteVeto(horaInicial, horaFinal));

        enderecoArea.setEditable(false);
        enderecoArea.setText(String.valueOf(mensagem.get(6)));

        diaEscolhe.setMinSelectableDate(diaInicial);
        diaEscolhe.setMaxSelectableDate(diaFinal);
    }

    public ProfissionalDataFrame() {

        addInfo(dia1, dia2);
        // System.out.println(String.valueOf(dia1).substring(0, 10));

        initComponents();
        enderecoArea.setEditable(false);
        enderecoArea.setText("qweasd");
        diaEscolhe.setMinSelectableDate(diaInicial);
        diaEscolhe.setMaxSelectableDate(diaFinal);
        setting.setVetoPolicy(new TesteVeto(LocalTime.of(20, 0), LocalTime.of(23, 0)));
    }

    private void addInfo(Object d1, Object d2) {
        try {
            diaInicial = new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(d1).substring(0, 10));
            diaFinal = new SimpleDateFormat("dd/MM/yyyy").parse(String.valueOf(d2).substring(0, 10));
        } catch (ParseException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

        horaInicial = LocalTime.parse(String.valueOf(d1).substring(11));
        horaFinal = LocalTime.parse(String.valueOf(d2).substring(11));

        setting.setAllowKeyboardEditing(false);
        setting.setAllowEmptyTimes(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        enderecoArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        diaEscolhe = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        horaEscolhe = new com.github.lgooddatepicker.components.TimePicker(setting);
        jLabel5 = new javax.swing.JLabel();
        enviarButton = new javax.swing.JButton();
        avisoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Endereço do cliente:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        enderecoArea.setColumns(20);
        enderecoArea.setRows(5);
        jScrollPane1.setViewportView(enderecoArea);

        jLabel2.setText("Escolha um dia e uma hora entre os mostrados abaixo para ir no cliente");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setText("Dia:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Hora:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        enviarButton.setText("Enviar");
        enviarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enviarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarButtonActionPerformed(evt);
            }
        });

        avisoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        avisoLabel.setForeground(new java.awt.Color(255, 0, 0));

        jButton1.setText("Voltar");
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2)))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avisoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaEscolhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaEscolhe, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enviarButton)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diaEscolhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(horaEscolhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(avisoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarButton)
                    .addComponent(jButton1))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 dispose();
        new HomeFrames().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enviarButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        String aviso = "";
        DateFormat dFormat = new SimpleDateFormat("dd/MM/yyyy");

        // horário
        if (horaEscolhe.getTime() == null)
            aviso = "Coloque o horário";
        // data
        if (diaEscolhe.getDate() == null)
            aviso = "Coloque o dia";

        avisoLabel.setText(aviso);
        repaint();

        if (aviso.length() == 0) {
            dispose();
            mensagem.set(9, dFormat.format(diaEscolhe.getDate()) + " " + horaEscolhe.getText());
            DocumentReference doc = ConectaFirebase.bd.collection("contratação").document((String) mensagem.get(10));
            doc.update("informações", mensagem);

            ArrayList<Object> aux = new ArrayList<Object>();
            aux.add(mensagem.get(0));
            aux.add(mensagem.get(1));
            aux.add(mensagem.get(3));
            aux.add(mensagem.get(4));
            aux.add(mensagem.get(6));
            aux.add(mensagem.get(9));
            aux.add(mensagem.get(2));
            aux.add(mensagem.get(5));
            new Historico().addHistorico((String) mensagem.get(0), true, aux);

            JOptionPane.showMessageDialog(null, "Mensagem enviada com sucesso");

            new HomeFrames().setVisible(true);

        }
    }// GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfissionalDataFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfissionalDataFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfissionalDataFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfissionalDataFrame.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfissionalDataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoLabel;
    private com.toedter.calendar.JDateChooser diaEscolhe;
    private javax.swing.JTextArea enderecoArea;
    private javax.swing.JButton enviarButton;
    private com.github.lgooddatepicker.components.TimePicker horaEscolhe;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
